import type { Metadata } from "next";
// @ts-ignore: side-effect CSS import without type declarations
import "./globals.css";
import Header from "./_components/header";
import { norwester, dmSans, glacialIndifference } from "./_fonts/fonts";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

// define our root layout
export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={`${norwester.variable} ${dmSans.variable} ${glacialIndifference.variable}`}
		>
			<body>
				<Header />

				{children}
			</body>
		</html>
	);
}
